thumbnail_convert_image:
    path: /thumbnail/call/{converter}/{path}
    controller: MrAuGir\Thumbnail\Action\ConvertImageController
    methods:
        - GET
    requirements:
        filter: '[A-z0-9_-]*'
        path: .+