services:
    _defaults:
        autowire: true
        autoconfigure: true

    MrAuGir\Thumbnail\Converter\:
        resource: '../../Converter/*'
        public: true

    MrAuGir\Thumbnail\Engine:
        public: true
        tags: ['mraugir.thumbnail.engine']