services:
    _defaults:
        autowire: true
        autoconfigure: true

    MrAuGir\Thumbnail\Processor\:
        resource: '../../Processor/*'

    MrAuGir\Thumbnail\Action\:
        resource: '../../Action/*'
        exclude:
            - '../../Action/Input/'
            - '../../Action/Output/'
        public: true
        tags: ['controller.service_arguments']

    MrAuGir\Thumbnail\Converter\:
        resource: '../../Converter/*'
        public: true

    MrAuGir\Thumbnail\ImageFileManager:
        arguments:
            $allowedHosts: '%thumbnail.allowed_hosts%'
            $fetchTimeout: '%thumbnail.fetch_timeout%'
            $maxFileSize: '%thumbnail.max_file_size%'

    MrAuGir\Thumbnail\Factory\ImageFactory:
        arguments:
            $imageFileManager: '@MrAuGir\Thumbnail\ImageFileManager'

    MrAuGir\Thumbnail\Engine:
        public: true
        arguments:
            $processTimeout: '%thumbnail.process_timeout%'
        tags: ['mraugir.thumbnail.engine']